# Generated by Django 6.0.4 on 2026-05-10 17:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('icon_marker', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='FoodPlace',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('name', models.CharField(max_length=255, verbose_name='Tên quán')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('category', models.ForeignKey(db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='storefront.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thongtinquanan',
            },
        ),
        migrations.CreateModel(
            name='FoodPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_places/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='storefront.foodplace')),
            ],
            options={
                'db_table': 'food_place_image',
            },
        ),
    ]
